/**
 * MSP:
 * - https://betaflight.com/docs/development/MSP-Protocol-Reference-Dev
 * -
 * https://github.com/DroneWuKong/drone-integration-handbook/blob/main/firmware/msp-protocol.md
 *
 * Typical MSP protocol loop:
 *
 * Host (configurator) sends init sequence to client (flight controller):
 *  -> 1, 2, 3, 5, 4, 101, 106
 *
 *
 * 1. Connection Initialization: API Handshake
 * 2. Firmware Variant Name Identification
 * 3. Firmware Generation Version Release Target
 * 4. Structural Hardware Platform Identifier
 * 5. Silicon UUID Verification Tracking
 * 6. Base Runtime State Metrics
 * 7. Unique Device Identifier for the Flight Controller
 */

#include "dev_msp_handler.hpp"

#include "stm_hal_shims.hpp"

// #include "usbd_cdc_if.h" // Generated by CubeMX for USB Virtual COM Port
// transmissions
#include <cstring>

extern StmConsole console;

MspHandler::MspHandler()
    : _state(State::WAIT_START),
      payload_size_(0),
      cmd_(0),
      payload_index_(0),
      checksum_(0) {}

void MspHandler::processByte(uint8_t byte) {
  switch (_state) {
    case State::WAIT_START:
      if (byte == '$') _state = State::WAIT_M;
      break;

    case State::WAIT_M:
      _state = (byte == 'M') ? State::WAIT_ARROW : State::WAIT_START;
      break;

    case State::WAIT_ARROW:
      // '<' indicates an incoming request/command directed to the flight
      // controller
      _state = (byte == '<') ? State::READ_SIZE : State::WAIT_START;
      break;

    case State::READ_SIZE:
      payload_size_ = byte;
      checksum_ = byte;  // Checksum resets and starts XOR calculation with size
      payload_index_ = 0;
      _state = State::READ_CMD;
      break;

    case State::READ_CMD:
      cmd_ = byte;
      checksum_ ^= byte;
      if (payload_size_ == 0) {
        _state = State::READ_CRC;
      } else {
        _state = State::READ_PAYLOAD;
      }
      break;

    case State::READ_PAYLOAD:
      rx_buffer_[payload_index_++] = byte;
      checksum_ ^= byte;
      if (payload_index_ >= payload_size_) {
        _state = State::READ_CRC;
      }
      break;

    case State::READ_CRC:
      if (byte == checksum_) {
        if (1) {
          int len;
          static uint8_t buf[64];
          len = snprintf((char*)buf, sizeof(buf), "MSP:%d \r\n", cmd_);
          console.Send((const char*)buf, len);
        }
        handleCommand(cmd_);  // CRC Verified! Execute command logic.
      }
      _state = State::WAIT_START;
      break;
  }
}

void MspHandler::handleCommand(uint8_t cmd) {
  switch (cmd) {
    // 1. Connection Initialization: API Handshake
    case 1: {  // MSP_API_VERSION (3b)
      struct __attribute__((packed)) MspApiVersionResponse {
        uint8_t mspProtocolVersion = 0;
        uint8_t apiVersionMajor = 1;
        uint8_t apiVersionMinor = 44;  // Modern Configurator safe API level
      } apiPacket;
      sendPacket(1, reinterpret_cast<uint8_t*>(&apiPacket), sizeof(apiPacket));
      break;
    }

    // 2. Firmware Variant Name Identification
    case 2: {  // MSP_FC_VARIANT (null term)
      uint8_t variantPacket[4] = {
          'B', 'T', 'F', 'L'};  // Locks into Betaflight layout expectations
      sendPacket(2, variantPacket, 4);
      break;
    }

    // 3. Firmware Generation Version Release Target
    case 3: {  // MSP_FC_VERSION (3b + null term)
      struct __attribute__((packed)) MspFcVersionResponse {
        uint8_t major = 4;
        uint8_t minor = 4;
        uint8_t patch = 0;
        uint8_t str[5] = {'H', 'B', 'R', 'O', '\0'};
      } versionPacket;
      sendPacket(3, reinterpret_cast<uint8_t*>(&versionPacket),
                 sizeof(versionPacket));
      break;
    }

    // 5. Structural Hardware Platform Identifier
    case 4: {  // MSP_BOARD_INFO
      struct __attribute__((packed)) MspBoardInfoResponse {
        uint8_t boardIdentifier[4] = {'H', 'B', 'R', 'O'};
        uint16_t hardwareRevision = 0;
        uint8_t osdType = 0;
        uint8_t multiwiiCapabilities = 0;
        uint8_t targetNameLength = 10;
        uint8_t targetName[11] = {'K', 'A', 'K', 'U', 'T', 'E', 'F', '4', 'V', '2', '\0'};
      } boardPacket;
      sendPacket(4, reinterpret_cast<uint8_t*>(&boardPacket),
                 sizeof(boardPacket));
      break;
    }

    // 4. Build Information / Firmware Generation Metadata
    case 5: {  // MSP_BUILD_INFO
      struct __attribute__((packed)) MspBuildInfoResponse {
        uint8_t buildDate[11] = {'2', '0', '2', '4', '-', '0', '6', '-', '1',
                                 '5', '\0'};
        uint8_t buildTime[9] = {'1', '2', ':', '3', '0', ':', '0', '0', '\0'};
        uint8_t gitHash[7] = {'a', 'b', 'c', 'd', 'e', 'f', '\0'};
        
      } buildInfoPacket;
      sendPacket(5, reinterpret_cast<uint8_t*>(&buildInfoPacket), sizeof(buildInfoPacket));
      break;
    }

    // 6. Base Runtime State Metrics
    case 101: {  // MSP_STATUS
      struct __attribute__((packed)) MspStatusResponse {
        uint16_t cycleTime = 200;
        uint16_t i2cErrorCounter = 0;
        uint16_t sensorFlags =
            0x03;  // Forces Accel (0x01) and Gyro (0x02) online
        uint32_t flightModeFlags = 0;
        uint8_t profileIndex = 0;
      } statusPacket;
      sendPacket(101, reinterpret_cast<uint8_t*>(&statusPacket),
                 sizeof(statusPacket));
      break;
    }

    // 7. unique device identifier for the flight controller
    case 160: {  // MSP_UID
      struct __attribute__((packed)) MspUidResponse {
        uint32_t uid[3] = {0x12345678, 0x9ABCDEF0, 0x00112233};
      } uidPacket;
      sendPacket(160, reinterpret_cast<uint8_t*>(&uidPacket),
                 sizeof(uidPacket));
      break;
    }

    // 10, 99, 246, 36, 32, 80, 70, 79, 240
    // 150, 110, 130, 116

    // MSP_FEATURE_CONFIG (36)
    // MSP_MIXER_CONFIG (42)
    // MSP_BOXNAMES (116)
    // MSP_PIDNAMES (117)

    // MSP_FC_RESOURCES (61)
    // MSP_SETTINGS_INFO (62)
    // MSP_DATA_FLASH_SUMMARY (70)

    // MSP_RC_TUNING (111)
    // MSP_PID (112)

    default:
      // Fallback acknowledgment loop tells the parser the feature field is
      // clear/empty
      sendPacket(cmd, nullptr, 0);
      break;
  }
}

void MspHandler::sendPacket(uint8_t cmd, const uint8_t* payload, uint8_t size) {
  // Maximum MSP V1 size is 5 header bytes + 255 payload bytes + 1 CRC byte =
  // 261 bytes

  tx_buffer_[0] = '$';
  tx_buffer_[1] = 'M';
  tx_buffer_[2] = '>';
  tx_buffer_[3] = size;
  tx_buffer_[4] = cmd;

  uint8_t calcCrc = size ^ cmd;

  for (uint8_t i = 0; i < size; ++i) {
    tx_buffer_[5 + i] = payload[i];
    calcCrc ^= payload[i];
  }

  tx_buffer_[5 + size] = calcCrc;

  // Send the complete, continuous packet frame layout down the USB line as ONE
  // bundle. This stops Windows/Linux serial drivers from misinterpreting raw
  // byte separations.
  CDC_Transmit_FS(tx_buffer_, 6 + size);

  // Give the hardware serial stack endpoints a brief moment to settle if
  // processing quickly
  // HAL_Delay(1);
}

void MspHandler::sendImuData(float ax, float ay, float az, float gx, float gy,
                             float gz) {
  struct __attribute__((packed)) MspImuResponse {
    int16_t accX;
    int16_t accY;
    int16_t accZ;
    int16_t gyroX;
    int16_t gyroY;
    int16_t gyroZ;
  } imuPacket;

  // Betaflight assumes specific raw integer multipliers:
  // Accelerometer scales to 1G = 512 units.
  // Gyroscope scales to 1 unit = 1/4th degree per second.
  imuPacket.accX = static_cast<int16_t>(ax * 512.0f);
  imuPacket.accY = static_cast<int16_t>(ay * 512.0f);
  imuPacket.accZ = static_cast<int16_t>(az * 512.0f);
  imuPacket.gyroX = static_cast<int16_t>(gx * 4.0f);
  imuPacket.gyroY = static_cast<int16_t>(gy * 4.0f);
  imuPacket.gyroZ = static_cast<int16_t>(gz * 4.0f);

  sendPacket(MSP_RAW_IMU, reinterpret_cast<uint8_t*>(&imuPacket),
             sizeof(imuPacket));
}
